FROM node:18-bullseye AS builder

# Install golang into builder image
ENV GO_VERSION=1.19.4 \
    GOPATH=$HOME/go-packages \
    GOROOT=$HOME/go
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH
RUN curl -fsSL https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | tar -xzv

WORKDIR /opt/app

# Process JavaScript part
# Copy in two parts to speed up re-builds to avoid additional npm install every time
COPY package.json /opt/app/
COPY renovate.json /opt/app/
RUN npm install
COPY ui /opt/app/ui/
RUN yarn build

# Compile GO parts
COPY go.mod /opt/app/
COPY go.sum /opt/app/
COPY main.go /opt/app/
COPY pkg /opt/app/pkg/
RUN go mod tidy
RUN go generate
RUN go build -tags="json1" -o xbvr main.go


# Target image
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder --chown=root:root /opt/app/xbvr /usr/bin/xbvr

EXPOSE 9998-9999
VOLUME /root/.config/

CMD ["/usr/bin/xbvr"]

